### PR TITLE
Fixnum -> Integer for Ruby 2.4+

### LINKED ISSUE #3: Fixnum is deprecated
When using the new Ruby 2.4, `/usr/local/lib/ruby/gems/2.4.0/gems/timerizer-0.1.4/lib/timerizer.rb:767: warning: constant ::Fixnum is deprecated`

### PR DESCRIPTION
**Pull request by elifoster**
Closes #3

### CODE REVIEW

**Comment by kylewlacy** [comment]
Thanks for the PR, looks good! Sorry it's taken me so long to review, but I'll get a new version uploaded when I get a chance (4 years is a reasonable time between releases, right?)

**Comment by elifoster** [comment]
@kylewlacy Any word on that new version?

**Comment by kylewlacy** [comment]
@elifoster Thanks for pinging me, it slipped my mind... the new version is up now!

Also, would you consent to me licensing your contributions under [the MIT license](https://choosealicense.com/licenses/mit/)? I didn't even realize the project didn't have a license until the `gem` CLI warned me about it

**Comment by elifoster** [comment]
Yes.

**Pull request merged**
